### ISSUE TITLE
'dict' object is not callable - when pringing JSON responses to terminal

### ISSUE THREAD

**Issue by infosec-au** [vnik5287/Crackq#2]
```
➜  Crackq git:(master) ./crackqcli.py -t lm 262b116e71c2c5d9c08226c21e62e5de
Enter your api key: _____________________...
Traceback (most recent call last):
  File "./crackqcli.py", line 112, in <module>
    print 'Results will be emailed to %s' % r.json()['email']
TypeError: 'dict' object is not callable
```
This error seems to be happening due to the fact that `r.json()` is being called. I believe to fix this, you must replace every instance of `r.json()` with `r.json`.

i.e. modified script:

![script](http://i.imgur.com/o22q6uK.png)

```
 Crackq git:(master) ✗ ./crackqcli.py -t ntlm af05ff4df8e67b453840d3a5674d7cbd
admin@shubh.am
```

This was on Kali linux.

**Comment by vnik5287** [comment]
read the INSTALL file :) the issue is related to the outdated 'requests' lib on Kali.

$ pip install requests --upgrade

For example, OS X has a newer requests lib version by default.

**Comment by infosec-au** [comment]
Thanks. Missed it.
